"""TXT → EPUB3 核心库：与前端无关，命令行与图形界面共用。

前端只做三件事：收集参数 → 调这里 → 展示结果。参数怎么翻译成 `Config` 看
`options.py`，有哪些活可以干看 `jobs.py`。
"""

from .._meta import __version__
from .builder import (
    COVER_SECTION_TYPE,
    build_css,
    build_epub,
    image_cover_body,
    text_cover_body,
)
from .cleaner import clean_line, clean_lines
from .config import (
    ALIGN_CHOICES,
    DEFAULT_CHAPTER_RE,
    DEFAULT_MAX_TITLE_LEN,
    DEFAULT_PREFACE_TITLE,
    DEFAULT_TOC_DEPTH,
    DEFAULT_VOLUME_RE,
    FALLBACK_TITLE,
    LEVEL_FIELDS,
    LEVEL_PRESETS,
    Config,
    LevelRule,
    Node,
    default_levels,
)
from .encoding import (
    AUTO_ENCODING,
    ENCODING_CHOICES,
    FALLBACK_ENCODINGS,
    EncodingError,
    decode,
    read_lines,
)
from .jobs import (
    STDOUT,
    Book,
    epub_path,
    generate,
    guard_overwrite,
    load,
    preview,
    render_toc,
    summary,
    toc_target,
    write_text,
)
from .levels import build_levels, check_pattern, parse_level_spec
from .mediatypes import (
    COVER_TYPES,
    FONT_TYPES,
    cover_media_type,
    find_cover,
    font_media_type,
)
from .meta import guess_metadata, resolve_metadata
from .options import (
    BOOL,
    CHOICE,
    INT,
    MULTI,
    PATH,
    TEXT,
    TOC_FORMATS,
    OPTIONS,
    Option,
    build_config,
    option_default,
    option_defaults,
    option_groups,
)
from .parser import NoEnabledRulesError, ParseStats, parse, walk
from .pipeline import process
from .replace import (
    DEFAULT_SCOPE,
    SCOPE_ALL,
    SCOPE_BODY,
    SCOPE_CHOICES,
    SCOPE_LABELS,
    SCOPE_TITLE,
    Replacer,
    Rule,
    check_scope,
    replacers_by_scope,
    rules_from_json,
    rules_from_rows,
    rules_from_source,
    rules_to_json,
)
from .toc import to_json, to_text

__all__ = [
    "ALIGN_CHOICES",
    "AUTO_ENCODING",
    "BOOL",
    "CHOICE",
    "COVER_SECTION_TYPE",
    "COVER_TYPES",
    "DEFAULT_CHAPTER_RE",
    "DEFAULT_MAX_TITLE_LEN",
    "DEFAULT_PREFACE_TITLE",
    "DEFAULT_SCOPE",
    "DEFAULT_TOC_DEPTH",
    "DEFAULT_VOLUME_RE",
    "ENCODING_CHOICES",
    "FALLBACK_ENCODINGS",
    "FALLBACK_TITLE",
    "FONT_TYPES",
    "INT",
    "LEVEL_FIELDS",
    "LEVEL_PRESETS",
    "MULTI",
    "OPTIONS",
    "PATH",
    "SCOPE_ALL",
    "SCOPE_BODY",
    "SCOPE_CHOICES",
    "SCOPE_LABELS",
    "SCOPE_TITLE",
    "STDOUT",
    "TEXT",
    "TOC_FORMATS",
    "Book",
    "Config",
    "EncodingError",
    "LevelRule",
    "NoEnabledRulesError",
    "Node",
    "Option",
    "ParseStats",
    "Replacer",
    "Rule",
    "__version__",
    "build_config",
    "build_css",
    "build_epub",
    "build_levels",
    "check_pattern",
    "check_scope",
    "clean_line",
    "clean_lines",
    "cover_media_type",
    "decode",
    "default_levels",
    "epub_path",
    "find_cover",
    "font_media_type",
    "generate",
    "guess_metadata",
    "guard_overwrite",
    "image_cover_body",
    "load",
    "option_default",
    "option_defaults",
    "option_groups",
    "parse",
    "parse_level_spec",
    "preview",
    "process",
    "read_lines",
    "render_toc",
    "replacers_by_scope",
    "resolve_metadata",
    "rules_from_json",
    "rules_from_rows",
    "rules_from_source",
    "rules_to_json",
    "summary",
    "text_cover_body",
    "to_json",
    "to_text",
    "toc_target",
    "walk",
    "write_text",
]
